target: adding support for Caldigit hotspot
helium/gateway-rs pull request #176
Opened 2022-01-19 17:09 UTC by alenhsu038

This is pull request for Caldigit light hotspot. I will use this repo's binary release to upgrade the gateway-rs in my system.

It has include the settings.toml for my ECC chip already. Please review and comment this PR..Thanks

BR,
Alen

2022-01-20 13:26 UTC, madninja approved these changes

2022-01-20 13:27 UTC, madninja requested changes
You failed to add the build to the build workflow

2022-01-20 15:14 UTC, alenhsu038 commented
Hi,
   I just updated missing ci.yml for workflow. Sorry for the inconvenience.
BR,
Alen

2022-01-21 15:16 UTC, madninja approved these changes

2022-01-21 15:16 UTC, merged