Update Readme regarding location assertion
helium/gateway-rs pull request #267
Opened 2022-06-28 09:11 UTC by Oliv4945

As discussed in #266 this adds a note so users now that gateway location assertion is now mandatory for downlinks

2022-08-04 22:10 UTC, JayKickliter requested changes

2022-08-04 22:10 UTC, JayKickliter commented on README.md
> + **NOTE**: This regionnal setting is only used for uplinks, due to TX power regulations the gateway location needs to be asserted on the blockchain to be able to send downlinks. See [this documentati
First, a strictly grammar suggestion:
```suggestion
**NOTE**: This regional setting is only used for uplinks. Due to TX power regulations, the gateway location needs to be asserted on the blockchain to be able to send downlinks. See [this documentation](https://docs.helium.com/mine-hnt/data-only-hotspots) to assert a gateway location.
```

2022-08-04 22:10 UTC, JayKickliter commented on README.md
> + **NOTE**: This regionnal setting is only used for uplinks, due to TX power regulations the gateway location needs to be asserted on the blockchain to be able to send downlinks. See [this documentati
Secondly, don't you mean 

> This regional setting is only used for ~~uplinks~~ downlinks

?

2023-01-19 22:24 UTC, madninja commented
Fixed in [c587c4e](https://github.com/helium/gateway-rs/commit/c587c4ecef57ffec846d2d2879afe36a71c1472a)

2023-01-19 22:24 UTC, closed without merging